version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "81:81" 
  dropwizard:
    image: hello-dropwizard:latest
    
